# Generated by Django 4.0 on 2022-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0002_remove_task_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
