# Generated by Django 4.0 on 2022-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0003_alter_status_status_alter_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=20, verbose_name='Краткое описание'),
        ),
    ]
