# Generated by Django 4.0 on 2022-01-20 06:48

import To_Do_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0005_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[To_Do_list.models.MaxLengthValidator(200)], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=20, validators=[To_Do_list.models.MinLengthValidator(5)], verbose_name='Краткое описание'),
        ),
    ]
