# Generated by Django 4.0 on 2022-02-01 13:33

import To_Do_list.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0006_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.CharField(max_length=20, null=True, verbose_name='Дата начала')),
                ('date_end', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=20, validators=[To_Do_list.models.MinLengthValidator(5)], verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, validators=[To_Do_list.models.MaxLengthValidator(2000)], verbose_name='Описание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='To_Do_list.task', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
    ]
