# Generated by Django 4.0 on 2022-02-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0008_projectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='To_Do_list.project', verbose_name='Проект'),
        ),
    ]
