# Generated by Django 4.0 on 2022-02-20 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('To_Do_list', '0009_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='projects', through='To_Do_list.ProjectUser', to=settings.AUTH_USER_MODEL, verbose_name='Проекты'),
        ),
    ]
