# Generated by Django 4.0 on 2022-02-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('To_Do_list', '0010_project_participants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('project', 'user')},
        ),
    ]
